name: workflow

on: [push, pull_request]

jobs:
  lock:
    timeout-minutes: 10
    strategy:
      matrix:
        python-version:  ["3.8", "3.9", "3.10", "3.11"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry lock
      - uses: actions/cache@v2
        with:
          path: poetry.lock
          key: ${{ github.sha }}-${{ matrix.python-version }}
  pytest:
    timeout-minutes: 10
    needs: lock
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: poetry.lock
          key: ${{ github.sha }}-${{ matrix.python-version }}
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install --extras cli
      - run: poetry run pytest --verbose
  mypy:
    timeout-minutes: 10
    needs: lock
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: poetry.lock
          key: ${{ github.sha }}-${{ matrix.python-version }}
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install --extras cli
      - run: poetry run mypy
  isort:
    timeout-minutes: 10
    needs: lock
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - uses: actions/cache@v2
        with:
          path: poetry.lock
          key: ${{ github.sha }}-3.11
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install --extras cli
      - run: poetry run isort --check --diff src tests
  black:
    timeout-minutes: 10
    needs: lock
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - uses: actions/cache@v2
        with:
          path: poetry.lock
          key: ${{ github.sha }}-3.11
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install --extras cli
      - run: poetry run black --check src/ tests/
  ruff:
    timeout-minutes: 10
    needs: lock
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - uses: actions/cache@v2
        with:
          path: poetry.lock
          key: ${{ github.sha }}-3.11
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install --extras cli
      - run: poetry run ruff src/ tests/

